version: '3'

services:
  raspap:
    image: cyber5k/raspap:latest
    container_name: mistborn_production_raspap
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
    #env_file:
    #  - ../.envs/.production/.pihole
    #command: /start
    network_mode: host
    cap_add:
      - NET_ADMIN
      #- SYS_ADMIN
    volumes:
      - ../../mistborn_volumes/extra/raspap/etc-raspap:/etc/raspap
    restart: unless-stopped

networks:
  default:
    external:
      name: mistborn_default
